### PR TITLE
Add Google Webmaster Tools verification file.

### PR DESCRIPTION
**Pull request by stphndxn**

### CODE REVIEW

**Comment by jamescmartinez** [comment]
@stevemdixon Can we do this via DNS instead? Would be much cleaner than maintaining a file.

**Comment by stphndxn** [comment]
We can do it either with a HTML tag, our Domain name provider, Google Analytics or Google Tag Manager. As soon as it's verified, we can delete the file.

**Comment by jamescmartinez** [comment]
Not quite. If we delete the file it becomes unverified. PM me the DNS info
and I'll take care of it when I get to a computer.

**Comment by jamescmartinez** [comment]
@stevemdixon Did it work?

**Pull request closed without merging**
