### PR TITLE
Add Webmaster Central verification file.

### PR DESCRIPTION
**Pull request by stphndxn**

### CODE REVIEW

**Comment by jamescmartinez** [comment]
This won't work without a route in app.rb.

**Comment by jamescmartinez** [comment]
You can probably put this in public folder root and it may work without a route in app.rb. Give that a try, and make sure the url works. :)

**Comment by stevemdixon** [comment]
Has this been done, @jamescmartinez?

**Comment by jamescmartinez** [comment]
Nope. See my comment that I left previously.

**Pull request closed without merging**
